# Generated by Django 3.1.7 on 2021-04-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0004_songs'),
    ]

    operations = [
        migrations.CreateModel(
            name='audio_files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_Type', models.CharField(max_length=250)),
                ('song_Title', models.CharField(max_length=250)),
                ('upload_date', models.DateField()),
                ('upload_time', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='book',
        ),
        migrations.DeleteModel(
            name='data',
        ),
        migrations.AddField(
            model_name='songs',
            name='date',
            field=models.CharField(default='', editable=False, max_length=250),
        ),
        migrations.AddField(
            model_name='songs',
            name='time',
            field=models.CharField(default='', editable=False, max_length=250),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
