# Generated by Django 3.1.7 on 2021-04-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0005_auto_20210404_1054'),
    ]

    operations = [
        migrations.DeleteModel(
            name='audio_files',
        ),
        migrations.AlterField(
            model_name='songs',
            name='date',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='songs',
            name='time',
            field=models.CharField(default='', max_length=250),
        ),
    ]
