# Generated by Django 3.1.7 on 2021-04-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0006_auto_20210416_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_title', models.CharField(max_length=250)),
                ('d', models.CharField(default='', max_length=250)),
                ('t', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
